### ISSUE TITLE
Building as static iOS/macOS library

### ISSUE THREAD

**Issue by ghost** [breadwallet/breadwallet-core#18]
Hi! I'm trying to attach your perfect library to my project but I have some various issues in linking it via Xcode target. 

How can I prebuild it to just importing like ".framework"? Is it possible at all? Maybe there are some tutorials I missed.

Thanks!

**Comment by EBGToo** [comment]
breadwallet-core is now delivered as an Xcode project - see Swift/BRCore.xcodeproj.  For your development you can define an Xcode workspace with both your project and the BRCore project included.

**Comment by gl3nda85** [comment]
hi, to follow this up im looking to integrate this library into a flutter project would you be able to point me in the direction of things i need to understand to make this work with flutter?

Thanks loads
