### ISSUE TITLE
Bitpay Bitcoin invoices broken on IOS Breadwallet 3.0

### ISSUE THREAD

**Issue by teran-mckinney** [breadwallet/breadwallet-core#21]
I went to pay a Bitpay invoice with Bitcoin. Scanned the QR code, loaded the request, no issues. Tried to pay and it says "Invalid Bitcoin address".

App also doesn't embed the version into the about screen. This must be 3.0 according to the app store.

**Comment by teran-mckinney** [comment]
Hi! This is still the case. Bitpay payments seem to be totally broken with Breadwallet.

**Comment by ewerx** [comment]
This is fixed and will be released with the 3.0.1 update this week.

**Comment by teran-mckinney** [comment]
Excellent, thank you!
