### ISSUE TITLE
Testing Suite

### ISSUE THREAD

**Issue by igorgue** [breadwallet/breadwallet-core#26]
Any pointers how to run `test.c`?

I got to the point that I'm able to compile on android using `gradlew` but then I'm not sure how to run `test.c`.

`gradlew :app:externalNativeBuildBrdTestnetDebug`

From there I copy my library from `app/build/intermediates/cmake/brdTestnet/debug/obj`

But when I'm using it on `test.c` it doesn't link property, I'm sure I'm missing something simple.

`~/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -v test.c -L.`

```
Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8.0.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/6.0.2 -internal-isystem /usr/local/include -internal-isystem /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/6.0.2/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /home/igor/Code/breadwallet-android/app/src/main/jni/breadwallet-core -ferror-limit 19 -fmessage-length 190 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/test-6cd0a9.o -x c test.c
clang -cc1 version 6.0.2 based upon LLVM 6.0.2svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/6.0.2/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7.3.0/crtbegin.o -L. -L/home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/6.0.2/lib/linux/x86_64 -L/usr/lib/gcc/x86_64-linux-gnu/7.3.0 -L/usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu -L/home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../.. -L/lib -L/usr/lib /tmp/test-6cd0a9.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/7.3.0/crtend.o /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu/crtn.o
/tmp/test-6cd0a9.o: In function `BRSetTests':
test.c:(.text+0x210b): undefined reference to `BRSetNew'
test.c:(.text+0x2155): undefined reference to `BRSetAdd'
test.c:(.text+0x2176): undefined reference to `BRSetCount'
test.c:(.text+0x21d6): undefined reference to `BRSetGet'
test.c:(.text+0x224e): undefined reference to `BRSetRemove'
test.c:(.text+0x22ab): undefined reference to `BRSetCount'
test.c:(.text+0x230e): undefined reference to `BRSetRemove'
test.c:(.text+0x236b): undefined reference to `BRSetCount'
/tmp/test-6cd0a9.o: In function `BRBase58Tests':
test.c:(.text+0x2439): undefined reference to `BRBase58Decode'
test.c:(.text+0x2466): undefined reference to `BRBase58Decode'
```

And so on, for each one of the definitions...

**Comment by igorgue** [comment]
Well, now I'm able to compile it with this long command:

```╰─ LD_LIBRARY_PATH="`pwd`:${HOME}/Android/Sdk/ndk-bundle/platforms/android-28/arch-x86_64/usr/lib64" /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -o test test.c -DBITCOIN_TESTNET=1 -Woverflow -L. -l core-lib ${HOME}/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
In file included from test.c:28:
In file included from ./BRWallet.h:29:
./BRAddress.h:38:9: warning: testnet build [-W#pragma-messages]
#pragma message "testnet build"
        ^
1 warning generated.
/usr/bin/ld: error in /home/igor/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc(.eh_frame); no .eh_frame_hdr table will be created.
```

But it now segfaults:

```
LD_LIBRARY_PATH="`pwd`:${HOME}/Android/Sdk/ndk-bundle/platforms/android-28/arch-x86_64/usr/lib64" ./test
[1]    16114 segmentation fault (core dumped)  LD_LIBRARY_PATH= ./test
```

Then when I compile with debug symbols:

```
╰─ LD_LIBRARY_PATH="`pwd`:${HOME}/Android/Sdk/ndk-bundle/platforms/android-28/arch-x86_64/usr/lib64" /home/igor/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -g test.c -DBITCOIN_TESTNET=1 -Woverflow -L. -l core-lib ${HOME}/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
In file included from test.c:28:
In file included from ./BRWallet.h:29:
./BRAddress.h:38:9: warning: testnet build [-W#pragma-messages]
#pragma message "testnet build"
        ^
1 warning generated.
/usr/bin/ld: error in /home/igor/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc(.eh_frame); no .eh_frame_hdr table will be created.
```

```
╰─ LD_LIBRARY_PATH="`pwd`:${HOME}/Android/Sdk/ndk-bundle/platforms/android-28/arch-x86_64/usr/lib64" gdb a.out
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...done.
(gdb) run
Starting program: /home/igor/Code/hodl-wallet-android/app/src/main/jni/breadwallet-core/a.out 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7de1ca3 in elf_machine_rela (skip_ifunc=<optimized out>, reloc_addr_arg=0x4bd1d0, version=<optimized out>, sym=<optimized out>, reloc=0x403700, map=0x7ffff7ffe170)
    at ../sysdeps/x86_64/dl-machine.h:458
458	../sysdeps/x86_64/dl-machine.h: No such file or directory.
```

Any help would be welcome, I'm trying to add some tests to the library but without reliably running what's in already it it's harder.

**Comment by igorgue** [comment]
More debug information if you, output of `bt full`:

https://gist.github.com/igorgue/ae27a5d54e5347017d631ac4d19c29e1

**Comment by igorgue** [comment]
Help anyone?

**Comment by igorgue** [comment]
ARE YOU SERIOUS MAN???

**Comment by EBGToo** [comment]
Please look a 'Breadwallet Android' (https://github.com/breadwallet/breadwallet-android) to see how to embed 'Core' into an Android app.  You might start there and trim it down for your specific needs.

**Comment by igorgue** [comment]
@EBGToo Okay thanks that's what I did, I thought there was a way to run them in the console: https://github.com/hodlwallet/breadwallet-core/pull/3/commits/c38d9330c2af850bcf5a3223dff9926252d7ff85 ?

**Comment by igorgue** [comment]
Closing this since I was able to run them on my fork.
