### ISSUE TITLE
Derivation Path

### ISSUE THREAD

**Issue by Robco87** [breadwallet/breadwallet-core#41]
Is is possible to modify the derivation path and if so would that be done in BRBIP32sequence.c?

**Comment by EBGToo** [comment]
You are looking to generate keys for non-bitcoin currencies?  

For our latest 'Ethereum' release we define the following:

```
extern BRKey
derivePrivateKeyFromSeed (UInt512 seed, uint32_t index) {
    BRKey privateKey;
    
    // The BIP32 privateKey for m/44'/60'/0'/0/index
    BRBIP32PrivKeyPath(&privateKey, &seed, sizeof(UInt512), 5,
                       44 | BIP32_HARD,          // purpose  : BIP-44
                       60 | BIP32_HARD,          // coin_type: Ethereum
                       0 | BIP32_HARD,          // account  : <n/a>
                       0,                        // change   : not change
                       index);                   // index    :
    
    privateKey.compressed = 0;
    
    return privateKey;
}
```

You can define an analogous function for something besides 'Ethereum'.  Or call `BRBIP32PrivKeyPath()` with the arguments you need.

**Comment by Robco87** [comment]
It would be for bitcoin. 
I have a use case that needs to support some legacy addresses that were created using Bip49. 
Would using the above method be a simple as updated to:
BRBIP32PrivKeyPath(&privateKey, &seed, sizeof(UInt512), 5,
                       49 | BIP32_HARD,          
                       0 | BIP32_HARD,          //1 for testnet
                       0  | BIP32_HARD,         
                       0,                       
                       index);

**Comment by EBGToo** [comment]
Yes, it may very well be.  Certainly worth a try.

**Comment by Robco87** [comment]
This could work for the private key path, but when restoring wallets its setting up the master public key. Do I also need to modify the path when a master public key is generated?

**Comment by JasonCoombs** [comment]
> For our latest 'Ethereum' release we define the following:
>     // The BIP32 privateKey for m/44'/60'/0'/0/index
>     BRBIP32PrivKeyPath(&privateKey, &seed, sizeof(UInt512), 5,
>                        44 | BIP32_HARD,          // purpose  : BIP-44
>                        60 | BIP32_HARD,          // coin_type: Ethereum
>                        0  | BIP32_HARD,          // account  : <n/a>
>                        0,                        // change   : not change
>                        index);                   // index    :

See: https://github.com/breadwallet/breadwallet-core/issues/41

What was the ETH derivation path back in 2017, before BIP44 adoption by Bread Wallet?

Thanks.
