### ISSUE TITLE
Can't send bitcoin

### ISSUE THREAD

**Issue by joachimneumann** [breadwallet/breadwallet-core#42]
Hi, 

I have a strange bug in the BRD app for iOS version 3.11 Build 3.
The amount is 0.00025 BTC and the fee is 0.000091 BTC

I cannot send Bitcoin, see the attached screenshots

![image1](https://user-images.githubusercontent.com/5642225/56823628-b71a3380-6854-11e9-87b0-e8e221f0a869.png)

![image2](https://user-images.githubusercontent.com/5642225/56823639-bda8ab00-6854-11e9-8479-7b22c9bfecab.png)

**Comment by joachimneumann** [comment]
I am not entirely sure if this repository is the right place for my problem. If not, please point me to the right direction and close the issue.

**Comment by EBGToo** [comment]
Probably https://github.com/breadwallet/breadwallet-ios is the proper place for this issue.  I have contacted the primary developer for that repository and he has created an internal JIRA item for your issue.

**Comment by joachimneumann** [comment]
Thanks. He is welcome to contact me if he can’t reproduce  the bug - I scanned the wrong code at https://proofofexistence.com/detail/c9b474809368590bb4142ab35bd29d324a674969af3ac98b764ccee9c27d9d8b

**Comment by EBGToo** [comment]
Our JIRA item links to this GitHub issue, including your above comment.  I'll close this issue; the JIRA item will handle your report.  Thanks.
