### ISSUE TITLE
Restore not finding transactions

### ISSUE THREAD

**Issue by Robco87** [breadwallet/breadwallet-core#48]
Restoring a wallet with a modified derivation path does not restore transactions.

Where in core would I need to modify to ensure transactions are found in the Merkle blocks?

**Comment by EBGToo** [comment]
What derivation path are you using?

**Comment by Robco87** [comment]
m/49'/0'/0'/0

**Comment by Robco87** [comment]
Is there a specific area in the code you can point me to where the blocks are checked for past wallet transactions?

**Comment by EBGToo** [comment]
I will close this.  If it is still an issue; create another one.  As far as 'blocks are checked for ... wallet transaction'; this is the BRPeerManager sync process.
