### ISSUE TITLE
Libraries for Android

### ISSUE THREAD

**Issue by FaysalM** [breadwallet/breadwallet-core#6]
Hi Guys - 

I am working on forking this wallet for LTC and running into issues compiling the core. Is this the version that is also used for android, and if so, are there any instructions on how to compile in Android studio?

Also would you all be interested in porting this to LTC at all? Given all the recent developments into LTC, this may be great. I can lend a hand as much as possible. Currently the bitcoinj implementation is downright dangerous and your wallet is more of a public service to keep folks and their crypto safe!

p.s. I got the gradle build working, but the c libraries have issues with android studio.

**Comment by EBGToo** [comment]
breadwallet-core now includes an Android Studio project and is delivered as an 'Android Library'.  See Java/* for gradle-related files.  If you continue to have issues with the C libraries in AS, please let us know.
