### ISSUE TITLE
RSK integration

### ISSUE THREAD

**Issue by alepc253** [breadwallet/breadwallet-core#60]
I'm interested in integrating RSK network to Breadwallet. 
RSK is a fork of Ethereum and, therefore, I assume that cloning and adapting `ethereum` folder should be necessary (but not sure if enough). Am I right? 
Any guidance you can offer will be very helpful.

**Comment by EBGToo** [comment]
That is probably a suitable starting point.  However, the ethereum folder is itself decomposed into a number of submodules.  You might be able to use the lower level concepts and only clone/replace the higher level concepts (folders ewm, bcs, les).

You'll need to determine how to sync/validate the RSK network's blockchain.  The ethereum code offers four possibilities ranging from 'Breadwallet Service Assist' to full Ethereum Peer-to-Peer.  I suspect none of that applies to RSK.

**Comment by alepc253** [comment]
Thanks @EBGToo, can you tell me more about the sync/validation? where can I see that implemented for Ethereum? I guess this is the challenge here...

**Comment by EBGToo** [comment]
Syncing is a complex topic and **the topic** for blockchains.  Other than existing code you can find and scour for sync functionality, I do not know of a general reference.
